Repository 466-team1/OptionalKarmotrine, pull requests merged in 2022-11, with the labels that each got.

#1 SQL Initialization files.
  README.md
  docs/ER_Description_Karmotrine2.pdf
  docs/Relational_Schema_Karmotrine2.pdf
  docs/websiteproject.drawio
  sql/01-createTable.sql
  sql/02-insertData.sql
Labels: enhancement

#2 Website design
  html/FringeWeaver.html
  html/assets/Button.png
  html/assets/Button2.png
  html/assets/CRS1.png
  html/assets/CyberpunkWaifus.ttf
  html/assets/FringeWeaver.png
  html/assets/Logo.png
  html/assets/borderCALI.png
  html/assets/borderIMG.png
  html/assets/borderTECH.png
  html/assets/stylesheet.css
  html/index.html
Labels: enhancement

#4 Cart, Checkout, Stylesheet and Library update.
  html/FringeWeaver.html
  html/assets/Marsblast.png
  html/assets/stylesheet.css
  html/cart.html
  html/checkout.html
  html/index.html
Labels: enhancement

#8 Relational schema writeup update
  README.md
  docs/ER_Description_Karmotrine2.pdf
  docs/Relational_Schema_Karmotrine2.pdf
  docs/WebsiteERDiagram.drawio
  docs/WebsiteERDiagram.drawio.pdf
  docs/websiteproject.drawio
Labels: documentation

#11 Schema Update 2
  README.md
  docs/ER_Description_Karmotrine.pdf
  docs/ER_Description_Karmotrine2.pdf
  docs/WebsiteERDiagram.drawio
  docs/WebsiteERDiagram.drawio.pdf
  sql/01-createTable.sql
  sql/02-insertData.sql
Labels: documentation, enhancement

#12 Fully Session-Based Dynamic Drinks Page, Profile and Cart
  README.md
  cartdemo/cart-page.php
  cartdemo/drinksub.php
  cartdemo/index.php
  cartdemo/login.php
  docs/ER_Description_Karmotrine.pdf
  docs/ER_Description_Karmotrine2.pdf
  docs/Relational_Schema_Karmotrine2.pdf
  docs/WebsiteERDiagram.drawio
  docs/WebsiteERDiagram.drawio.pdf
  docs/websiteproject.drawio
  html/assets/drinksLib.php
  html/assets/profileLib.php
  html/cart.php
  html/cartAdd.php
  html/checkout.php
  html/drinkProfile.php
  html/drinks.php
  html/index.php
  html/updateCart.php
  lib/db.php
  lib/drinksLib.php
  lib/library.php
  sql/01-createTable.sql
  sql/02-insertData.sql
Labels: enhancement

#13 Fully working checkout page.
  README.md
  html/assets/nosignal.png
  html/cart.php
  html/checkout.php
  html/drinkProfile.php
  html/drinks.php
  html/index.php
  lib/drinksLib.php
  lib/library.php
  sql/03-insertSampleOrder.sql
Labels: enhancement

#10 Admin page
  employee.php
  html/employee.php
  html/employeeportal.php
  html/inventory.php
  html/ordertrack.php
Labels: enhancement

#15 Employee View and Find my Order pages
  html/cart.php
  html/checkout.php
  html/drinkProfile.php
  html/drinks.php
  html/employee.php
  html/index.php
  html/inventory.php
  html/orderTrack.php
  lib/drinksLib.php
Labels: enhancement

#14 Session variable overhaul with working admin and order lookup.
  README.md
  cartdemo/cart-page.php
  cartdemo/drinksub.php
  cartdemo/index.php
  cartdemo/login.php
  docs/ER_Description_Karmotrine.pdf
  docs/WebsiteERDiagram.drawio
  docs/WebsiteERDiagram.drawio.pdf
  html/FringeWeaver.html
  html/assets/Marsblast.png
  html/assets/annagraem.gif
  html/assets/drinks/Beer.png
  html/assets/drinks/ERROR.png
  html/assets/drinks/FlamingMoai.png
  html/assets/drinks/FluffyDream.png
  html/assets/drinks/FrothyWater.png
  html/assets/drinks/GutPunch.png
  html/assets/drinks/Mercuryblast.png
  html/assets/drinks/SparkleStar.png
  html/assets/drinks/SugarRush.png
  html/assets/drinks/SunshineCloud.png
  html/assets/drinks/ZenStar.png
  html/assets/drinksLib.php
  html/assets/favicon.ico
  html/assets/nosignal.png
  html/assets/stylesheet.css
  html/cart.html
  html/cart.php
  html/cartAdd.php
  html/checkout.php
  html/drinkProfile.php
  html/drinks.php
  html/employee.php
  html/index.php
  html/orderTrack.php
  html/updateCart.php
  lib/db.php
  lib/drinksLib.php
  lib/library.php
  sql/02-insertData.sql
  sql/03-insertSampleOrder.sql
Labels: enhancement
